<template>
  <section><div class="page-header"><div><p class="eyebrow">Schedule</p><h1>Availability</h1><p class="lede">All services share this capacity schedule in v1, so two services can never occupy the same slot.</p></div><button class="primary" type="button" :disabled="saving" @click="submit">{{ saving?'Saving…':'Save schedule' }}</button></div>
    <div v-if="notice" class="notice" role="status">{{ notice }}</div><div v-if="error" class="notice error" role="alert">{{ error }}</div>
    <div class="card controls"><div class="field"><label>Timezone</label><input v-model.trim="form.timezone" list="timezones" required><datalist id="timezones"><option value="Africa/Lagos"></option><option value="Europe/London"></option><option value="America/New_York"></option><option value="UTC"></option></datalist></div><div class="field"><label>Slot interval</label><select v-model.number="form.slotIntervalMinutes"><option v-for="value in [15,30,45,60,90,120]" :value="value" :key="value">{{ value }} minutes</option></select></div><div class="field"><label>Minimum notice</label><select v-model.number="form.minimumNoticeMinutes"><option :value="30">30 minutes</option><option :value="60">1 hour</option><option :value="240">4 hours</option><option :value="1440">1 day</option></select></div><div class="field"><label>Booking horizon</label><select v-model.number="form.bookingHorizonDays"><option :value="30">30 days</option><option :value="60">60 days</option><option :value="90">90 days</option></select></div></div>
    <div class="card days"><div v-for="day in days" :key="day.weekday" class="day"><label class="day-toggle"><input v-model="day.active" type="checkbox"><strong>{{ day.name }}</strong></label><div class="times"><input v-model="day.start" type="time" :disabled="!day.active" :aria-label="`${day.name} start`"><span>to</span><input v-model="day.end" type="time" :disabled="!day.active" :aria-label="`${day.name} end`"></div><span class="muted">{{ day.active?'Open':'Closed' }}</span></div></div>
  </section>
</template>
<script setup>
import { inject,onMounted,reactive,ref } from 'vue';import { saveSchedule } from '../booking.js'
const state=inject('bookingState'),refresh=inject('refreshBookings'),saving=ref(false),notice=ref(''),error=ref('')
const names=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],days=reactive(names.map((name,weekday)=>({name,weekday,active:weekday>0&&weekday<6,start:'09:00',end:'17:00'})))
const form=reactive({timezone:'Africa/Lagos',slotIntervalMinutes:30,minimumNoticeMinutes:60,bookingHorizonDays:60})
function minute(value){const [hour,part]=value.split(':').map(Number);return hour*60+part}function time(value){return `${String(Math.floor(value/60)).padStart(2,'0')}:${String(value%60).padStart(2,'0')}`}
onMounted(()=>{const existing=state.schedules[0];if(!existing)return;Object.assign(form,{timezone:existing.timezone,slotIntervalMinutes:Number(existing['slot_interval_minutes']),minimumNoticeMinutes:Number(existing['minimum_notice_minutes']),bookingHorizonDays:Number(existing['booking_horizon_days'])});try{const windows=JSON.parse(existing['weekly_windows_json']);days.forEach(day=>{const window=windows.find(item=>item.weekday===day.weekday);day.active=!!window;if(window){day.start=time(window.startMinute);day.end=time(window.endMinute)}})}catch{error.value='The saved weekly schedule needs repair.'}})
async function submit(){const weeklyWindows=days.filter(day=>day.active).map(day=>({weekday:day.weekday,startMinute:minute(day.start),endMinute:minute(day.end)}));if(!weeklyWindows.length){error.value='Open at least one day.';return}if(weeklyWindows.some(item=>item.startMinute>=item.endMinute)){error.value='Every open day needs an end time after its start time.';return}saving.value=true;error.value='';try{await saveSchedule(state.schedules[0],{name:'Working hours',...form,weeklyWindows});await refresh();notice.value='Availability saved.'}catch(reason){error.value=reason?.message||'Availability could not be saved.'}finally{saving.value=false;setTimeout(()=>notice.value='',2000)}}
</script>
<style scoped>.controls{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin-bottom:16px}.controls .field{margin:0}.days{padding:0;overflow:hidden}.day{display:grid;grid-template-columns:1fr 2fr 90px;gap:18px;align-items:center;padding:15px 20px;border-bottom:1px solid var(--line)}.day:last-child{border:0}.day-toggle{display:flex;align-items:center;gap:10px}.day-toggle input{width:18px;min-height:18px}.times{display:flex;align-items:center;gap:9px}.times input{width:145px;padding:0 10px;border:1px solid #b9bece;border-radius:9px}@media(max-width:760px){.controls{grid-template-columns:1fr 1fr}.day{grid-template-columns:1fr}.times input{min-width:0;flex:1}.day>.muted{display:none}}@media(max-width:480px){.controls{grid-template-columns:1fr}}
</style>
