<template>
  <section><div class="page-header"><div><p class="eyebrow">Operations</p><h1>Bookings</h1><p class="lede">Confirmed appointments are the source of truth. Cancellation frees the slot but keeps the record.</p></div><select v-model="filter" aria-label="Filter bookings"><option value="all">All bookings</option><option value="confirmed">Confirmed</option><option value="cancelled">Cancelled</option></select></div>
    <div v-if="notice" class="notice" role="status">{{ notice }}</div><div v-if="error" class="notice error" role="alert">{{ error }}</div>
    <div v-if="filtered.length" class="booking-list"><article v-for="booking in filtered" :key="booking.id" class="card booking"><div class="date"><strong>{{ day(booking['starts-at']) }}</strong><span>{{ month(booking['starts-at']) }}</span></div><div class="booking-main"><span class="chip" :class="booking.status">{{ booking.status }}</span><h2>{{ booking['service-name'] }}</h2><p class="muted">{{ when(booking) }} · {{ booking.timezone }}</p><p>{{ booking['guest-name'] }} · {{ booking['guest-email'] }}</p></div><button class="secondary" type="button" @click="selected=booking">View</button></article></div>
    <div v-else class="empty"><h2>No {{ filter==='all'?'':filter }} bookings</h2><p class="muted">A successful guest booking will appear here after the server reserves its slot.</p></div>
    <div v-if="selected" class="modal-backdrop" @click.self="close"><aside class="card modal" aria-label="Booking details"><p class="eyebrow">Booking {{ selected.reference }}</p><h2>{{ selected['service-name'] }}</h2><dl><div><dt>When</dt><dd>{{ when(selected) }} {{ selected.timezone }}</dd></div><div><dt>Guest</dt><dd>{{ selected['guest-name'] }} · {{ selected['guest-email'] }}</dd></div><div><dt>Phone</dt><dd>{{ selected['guest-phone'] || 'Not supplied' }}</dd></div><div><dt>Notes</dt><dd>{{ selected.notes || 'No notes' }}</dd></div></dl><div v-if="confirmCancel" class="confirm-box"><strong>Cancel and reopen this slot?</strong><p class="muted">The booking stays in history.</p><div class="form-actions"><button class="danger" type="button" @click="cancel">Yes, cancel booking</button><button class="secondary" type="button" @click="confirmCancel=false">Keep booking</button></div></div><div v-else class="form-actions"><button v-if="selected.status!=='cancelled'" class="danger" type="button" @click="confirmCancel=true">Cancel booking</button><button class="secondary" type="button" @click="close">Close</button></div></aside></div>
  </section>
</template>
<script setup>
import { computed,inject,ref } from 'vue';import { cancelBooking } from '../booking.js'
const state=inject('bookingState'),refresh=inject('refreshBookings'),filter=ref('all'),selected=ref(null),confirmCancel=ref(false),notice=ref(''),error=ref('')
const filtered=computed(()=>state.bookings.filter(item=>filter.value==='all'||item.status===filter.value).sort((a,b)=>Date.parse(a['starts-at'])-Date.parse(b['starts-at'])))
function parsed(value){return new Date(value)}function day(value){return parsed(value).toLocaleDateString(undefined,{day:'2-digit'})}function month(value){return parsed(value).toLocaleDateString(undefined,{month:'short'})}function when(value){return parsed(value['starts-at']).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'})}
function close(){selected.value=null;confirmCancel.value=false}
async function cancel(){error.value='';try{await cancelBooking(selected.value,'Cancelled by owner');await refresh();notice.value='Booking cancelled and slot reopened.';close()}catch(reason){error.value=reason?.message||'Booking could not be cancelled.'}}
</script>
<style scoped>.page-header select{width:180px;padding:0 10px;border:1px solid var(--line);border-radius:10px;background:#fff}.booking-list{display:grid;gap:12px}.booking{display:grid;grid-template-columns:70px 1fr auto;align-items:center;gap:18px}.date{display:grid;place-items:center;padding:11px;border-radius:12px;background:var(--accent-soft)}.date strong{font-size:25px}.date span{color:var(--muted);font-size:12px;text-transform:uppercase}.booking-main h2{margin:8px 0 4px}.booking-main p{margin-bottom:4px}.modal dl{display:grid;gap:14px}.modal dl div{padding-bottom:12px;border-bottom:1px solid var(--line)}dt{color:var(--muted);font-size:12px;font-weight:800;text-transform:uppercase}dd{margin:5px 0 0}.confirm-box{padding:16px;margin-top:20px;border-radius:12px;background:#fff5f4}.confirm-box p{margin:5px 0 12px}@media(max-width:620px){.booking{grid-template-columns:58px 1fr}.booking>button{grid-column:1/-1}.page-header select{width:100%}}
</style>
