<template>
  <div class="public-shell"><header><div class="public-brand"><span>B</span>Bookings</div><small>Secure booking link</small></header><main>
    <div v-if="loading" class="public-state"><div class="spinner"></div><h1>Opening booking page…</h1></div>
    <div v-else-if="error" class="public-state error"><h1>This booking link is unavailable.</h1><p>{{ error }}</p><button class="secondary" type="button" @click="start">Try again</button></div>
    <template v-else-if="!confirmation"><section class="profile"><img v-if="page.profile.photoUrl" :src="page.profile.photoUrl" alt=""><div><p class="eyebrow">Book a service</p><h1>{{ page.profile.displayName }}</h1><p>{{ page.profile.bio }}</p><span>{{ page.profile.timezone }}</span></div></section>
      <div class="booking-layout"><aside><h2>Choose a service</h2><button v-for="service in page.services" :key="service.id" class="service-choice" :class="{active:selectedService?.id===service.id}" type="button" @click="choose(service)"><strong>{{ service.name }}</strong><span>{{ service.durationMinutes }} min · {{ service.price?`${service.price} ${service.currency}, arranged with owner`:'Free' }}</span><small>{{ service.description }}</small></button></aside>
        <section class="booking-panel"><template v-if="selectedService"><div class="field"><label for="booking-start-date">Starting date</label><input id="booking-start-date" v-model="startDate" type="date" :min="today" @change="loadOpenings"></div><div v-if="slotsLoading" class="muted">Checking availability…</div><div v-else-if="openings.length" class="slots"><button v-for="slot in openings" :key="slot.startsAt" type="button" :class="{active:selectedSlot?.startsAt===slot.startsAt}" @click="selectedSlot=slot;submitError=''">{{ slotLabel(slot) }}</button></div><div v-else class="empty compact">No openings in this range. Try another date.</div>
          <form v-if="selectedSlot" @submit.prevent="submit"><h2>Your details</h2><p v-if="submitError" class="notice error" role="alert">{{ submitError }}</p><div class="field"><label for="booking-guest-name">Name</label><input id="booking-guest-name" v-model.trim="contact.name" required maxlength="160"></div><div class="field"><label for="booking-guest-email">Email</label><input id="booking-guest-email" v-model.trim="contact.email" type="email" required maxlength="254"></div><div class="field"><label for="booking-guest-phone">Phone</label><input id="booking-guest-phone" v-model.trim="contact.phone" maxlength="40"></div><div class="field"><label for="booking-guest-notes">Notes</label><textarea id="booking-guest-notes" v-model.trim="notes" maxlength="2000"></textarea></div><button class="primary" :disabled="submitting">{{ submitting?'Confirming…':'Confirm booking' }}</button><p class="fine-print">Confirmation appears on screen. Email, Calendar, and online payment are not promised by this release.</p></form></template><div v-else class="public-state small"><h2>Choose a service to see openings.</h2></div></section></div></template>
    <div v-else class="confirmation"><span class="check">✓</span><p class="eyebrow">Booking confirmed</p><h1>{{ confirmation.serviceName }}</h1><p class="when">{{ new Date(confirmation.startsAt).toLocaleString(undefined,{dateStyle:'full',timeStyle:'short'}) }}</p><dl><div><dt>Reference</dt><dd>{{ confirmation.reference }}</dd></div><div><dt>Timezone</dt><dd>{{ confirmation.timezone }}</dd></div><div><dt>Delivery</dt><dd>Confirmed on this screen</dd></div></dl><p class="muted">Save this page or reference. The owner can see the booking in Goalmatic.</p></div>
  </main></div>
</template>
<script setup>
import { computed,onMounted,reactive,ref } from 'vue';import { loadGuestOpenings,loadGuestPage,submitGuestBooking } from '../booking.js'
const loading=ref(true),error=ref(''),submitError=ref(''),page=ref(null),selectedService=ref(null),openings=ref([]),selectedSlot=ref(null),slotsLoading=ref(false),submitting=ref(false),confirmation=ref(null),notes=ref(''),contact=reactive({name:'',email:'',phone:''})
const today=new Date().toISOString().slice(0,10),startDate=ref(new Date(Date.now()+86400000).toISOString().slice(0,10))
function plusDays(date,count){const value=new Date(`${date}T00:00:00Z`);value.setUTCDate(value.getUTCDate()+count);return value.toISOString().slice(0,10)}
async function start(){loading.value=true;error.value='';try{page.value=await loadGuestPage();if(page.value.services.length===1)await choose(page.value.services[0])}catch(reason){error.value=reason?.message||'Ask the owner for a new booking link.'}finally{loading.value=false}}
async function choose(service){selectedService.value=service;selectedSlot.value=null;await loadOpenings()}
async function loadOpenings(){if(!selectedService.value)return;slotsLoading.value=true;error.value='';try{const result=await loadGuestOpenings(selectedService.value.id,startDate.value,plusDays(startDate.value,6));openings.value=(result.openings||[]).slice(0,24)}catch(reason){error.value=reason?.message||'Availability could not load.'}finally{slotsLoading.value=false}}
function slotLabel(slot){return new Date(slot.startsAt).toLocaleString(undefined,{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}
async function submit(){submitting.value=true;submitError.value='';try{confirmation.value=await submitGuestBooking({serviceId:selectedService.value.id,startsAt:selectedSlot.value.startsAt,contact:{...contact},notes:notes.value},crypto.randomUUID())}catch(reason){const message=reason?.message||'That slot could not be booked. Choose another.';await loadOpenings();submitError.value=message}finally{submitting.value=false}}
onMounted(start)
</script>
<style scoped>.public-shell{min-height:100vh;color:#171b2d;background:linear-gradient(180deg,#f1f2ff,#fff 42%)}header{height:70px;padding:0 max(22px,calc((100vw - 1180px)/2));display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #dfe2ee;background:rgba(255,255,255,.86)}.public-brand{display:flex;align-items:center;gap:9px;font-weight:850}.public-brand span{display:grid;place-items:center;width:32px;height:32px;border-radius:10px;color:#fff;background:#3346db}header small{color:#697087}main{max-width:1180px;margin:0 auto;padding:50px 22px 70px}.profile{display:flex;gap:20px;align-items:center;margin-bottom:34px}.profile img{width:88px;height:88px;border-radius:24px;object-fit:cover}.profile h1{margin-bottom:7px}.profile p{max-width:62ch;color:#697087}.profile span{font-size:13px;color:#4b5570}.booking-layout{display:grid;grid-template-columns:360px 1fr;gap:18px}.booking-layout>aside,.booking-panel,.confirmation{padding:22px;border:1px solid #e0e3ec;border-radius:18px;background:#fff;box-shadow:0 16px 50px rgba(42,50,99,.08)}.service-choice{width:100%;height:auto;min-height:96px;padding:14px;margin-bottom:9px;display:grid;gap:5px;text-align:left;border:1px solid #e1e3eb;border-radius:13px;background:#fff}.service-choice.active{border-color:#3346db;background:#f0f1ff}.service-choice span,.service-choice small{color:#697087}.slots{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-bottom:24px}.slots button{padding:9px;border:1px solid #dcdfea;border-radius:10px;background:#fff}.slots button.active{color:#fff;border-color:#3346db;background:#3346db}.fine-print{margin:14px 0 0;color:#697087;font-size:12px;line-height:1.5}.public-state,.confirmation{max-width:680px;margin:90px auto;text-align:center}.public-state.small{margin:90px auto}.spinner{width:34px;height:34px;margin:0 auto 20px;border:3px solid #daddf8;border-top-color:#3346db;border-radius:50%;animation:spin .8s linear infinite}.confirmation .check{display:grid;place-items:center;width:60px;height:60px;margin:0 auto 20px;border-radius:50%;color:#fff;background:#199762;font-size:30px}.confirmation .when{font-size:20px}.confirmation dl{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:25px 0}.confirmation dl div{padding:14px;border-radius:12px;background:#f5f6fa}.confirmation dt{color:#697087;font-size:11px;text-transform:uppercase}.confirmation dd{margin:6px 0 0;font-weight:800}.compact{padding:18px}@keyframes spin{to{transform:rotate(360deg)}}@media(max-width:800px){.booking-layout{grid-template-columns:1fr}.slots{grid-template-columns:1fr 1fr}.profile{align-items:flex-start}.confirmation dl{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){.spinner{animation:none}}
</style>
