<template>
  <section><div class="page-header"><div><p class="eyebrow">Catalog</p><h1>Services</h1><p class="lede">A service owns its duration, display price, visibility, and schedule.</p></div><button class="primary" type="button" @click="open()">New service</button></div>
    <div v-if="notice" class="notice" role="status">{{ notice }}</div><div v-if="error" class="notice error" role="alert">{{ error }}</div>
    <div v-if="state.services.length" class="service-list"><article v-for="service in state.services" :key="service.id" class="card service"><div><div class="service-meta"><span class="chip" :class="service.active!==false?'confirmed':''">{{ service.active!==false?'Active':'Paused' }}</span><span>{{ service['duration-minutes'] }} min</span><span>{{ service.price ? `${service.price} ${service.currency}` : 'Free' }}</span></div><h2>{{ service.name }}</h2><p class="muted">{{ service.description }}</p></div><div class="form-actions"><button class="secondary" type="button" @click="open(service)">Edit</button><button class="danger" type="button" @click="pendingDelete=service">Delete</button></div></article></div>
    <div v-else class="empty"><h2>No services yet</h2><p class="muted">Create one service after setting your weekly availability.</p><button class="primary" type="button" @click="open()">Create service</button></div>
    <div v-if="show" class="modal-backdrop" @click.self="show=false"><form class="card modal" @submit.prevent="submit"><p class="eyebrow">{{ editing?'Edit':'New' }} service</p><h2>{{ editing?'Update the offering':'Create a focused offering' }}</h2><div class="field"><label>Name</label><input v-model.trim="form.name" maxlength="100" required></div><div class="field"><label>Description</label><textarea v-model.trim="form.description" maxlength="1500" required></textarea></div><div class="grid grid-2"><div class="field"><label>Duration</label><select v-model.number="form.durationMinutes"><option v-for="value in durations" :key="value" :value="value">{{ value }} minutes</option></select></div><div class="field"><label>Display price</label><input v-model.number="form.price" type="number" min="0" step="1"></div></div><div class="grid grid-2"><div class="field"><label>Visibility</label><select v-model="form.visibility"><option value="public">Public link</option><option value="private">Private link only</option></select></div><div class="field"><label>Status</label><select v-model="form.active"><option :value="true">Active</option><option :value="false">Paused</option></select></div></div><p class="muted">Online payment is not collected in this release. Any non-zero price is shown as “arranged with owner”.</p><div class="form-actions"><button class="primary" :disabled="saving">{{ saving?'Saving…':'Save service' }}</button><button class="secondary" type="button" @click="show=false">Cancel</button></div></form></div>
    <div v-if="pendingDelete" class="modal-backdrop" @click.self="pendingDelete=null"><div class="card modal"><p class="eyebrow">Delete service</p><h2>Delete {{ pendingDelete.name }}?</h2><p class="muted">Existing booking records remain in history.</p><div class="form-actions"><button class="danger" type="button" @click="remove">Delete service</button><button class="secondary" type="button" @click="pendingDelete=null">Keep service</button></div></div></div>
  </section>
</template>
<script setup>
import { inject, reactive, ref } from 'vue';import { deleteService,saveService } from '../booking.js'
const state=inject('bookingState'),refresh=inject('refreshBookings'),show=ref(false),saving=ref(false),editing=ref(null),pendingDelete=ref(null),notice=ref(''),error=ref(''),durations=[15,30,45,60,90,120]
const form=reactive({name:'',description:'',durationMinutes:30,price:0,currency:'NGN',visibility:'public',active:true})
function open(service=null){error.value='';editing.value=service;Object.assign(form,service?{name:service.name,description:service.description,durationMinutes:service['duration-minutes'],price:service.price||0,currency:service.currency||'NGN',visibility:service.visibility,active:service.active!==false}:{name:'',description:'',durationMinutes:30,price:0,currency:'NGN',visibility:'public',active:true});show.value=true}
async function submit(){const schedule=state.schedules[0];if(!schedule){error.value='Set availability before creating a service.';show.value=false;return}if(form.durationMinutes>Number(schedule['slot-interval-minutes'])){error.value=`Duration must be ${schedule['slot-interval-minutes']} minutes or less for this schedule.`;return}saving.value=true;error.value='';try{await saveService(editing.value,{...form,scheduleId:schedule.id});await refresh();show.value=false;notice.value='Service saved.'}catch(reason){error.value=reason?.message||'Service could not be saved.'}finally{saving.value=false;setTimeout(()=>notice.value='',2000)}}
async function remove(){await deleteService(pendingDelete.value.id);pendingDelete.value=null;await refresh();notice.value='Service deleted.'}
</script>
<style scoped>.service-list{display:grid;gap:14px}.service{display:flex;justify-content:space-between;gap:20px;align-items:center}.service h2{margin:10px 0 7px}.service-meta{display:flex;gap:10px;align-items:center;color:var(--muted);font-size:12px}.notice.error{color:var(--danger)}@media(max-width:650px){.service{align-items:flex-start;flex-direction:column}}
</style>
