<template>
  <section><div class="page-header"><div><p class="eyebrow">Catalog</p><h1>Services</h1><p class="lede">Create the focused offerings guests can request. Nothing is published until you configure it here.</p></div><button class="button button-primary" type="button" @click="openForm">New service</button></div>
    <div v-if="notice" class="notice success" role="status">{{ notice }}</div><div v-if="error" class="notice error" role="alert">{{ error }}</div>
    <div v-if="workspace.services.length" class="service-list"><article v-for="service in workspace.services" :key="service.id" class="card service-row"><div><p class="card-label">{{ service.duration }} minutes · {{ service.price ? service.price + ' ' + service.currency : 'Price on request' }}</p><h2>{{ service.name }}</h2><p class="muted">{{ service.description }}</p></div><button class="button button-quiet danger" type="button" @click="remove(service.id)">Delete</button></article></div>
    <div v-else class="empty"><h2>Your catalog is empty</h2><p>Add your first service to give guests a bookable starting point.</p><button class="button button-primary" type="button" @click="openForm">Create first service</button></div>
    <div v-if="formOpen" class="modal-backdrop" @click.self="closeForm"><form class="modal card" @submit.prevent="create"><div><p class="eyebrow">New service</p><h2>Create a service</h2></div><div class="field"><label for="service-name">Name</label><input id="service-name" v-model.trim="form.name" required maxlength="80" /></div><div class="field"><label for="service-description">Description</label><textarea id="service-description" v-model.trim="form.description" required></textarea></div><div class="form-grid"><div class="field"><label for="duration">Duration (minutes)</label><input id="duration" v-model.number="form.duration" type="number" min="1" required /></div><div class="field"><label for="price">Price (optional)</label><input id="price" v-model.number="form.price" type="number" min="0" step="0.01" /></div></div><p v-if="error" class="error" role="alert">{{ error }}</p><div class="form-actions"><button class="button button-primary" type="submit" :disabled="saving">{{ saving ? 'Creating…' : 'Create service' }}</button><button class="button" type="button" @click="closeForm">Cancel</button></div></form></div>
  </section>
</template>
<script setup>
import { inject, reactive, ref } from 'vue'
const workspace=inject('workspace'), formOpen=ref(false), saving=ref(false), notice=ref(''), error=ref(''), form=reactive({name:'',description:'',duration:30,price:null})
function openForm(){error.value='';formOpen.value=true} function closeForm(){formOpen.value=false;error.value=''}
function create(){ if(!form.name||!form.description||!form.duration||form.duration<1){error.value='Add a name, description, and valid duration.';return} saving.value=true; setTimeout(()=>{workspace.services.push({id:Date.now(),name:form.name,description:form.description,duration:form.duration,price:form.price,currency:'USD'});Object.assign(form,{name:'',description:'',duration:30,price:null});saving.value=false;formOpen.value=false;notice.value='Service created in your workspace.';setTimeout(()=>notice.value='',3000)},350)}
function remove(id){workspace.services=workspace.services.filter(service=>service.id!==id);notice.value='Service removed.';setTimeout(()=>notice.value='',3000)}
</script>
<style scoped>.service-list{display:grid;gap:14px}.service-row{display:flex;justify-content:space-between;align-items:center;gap:18px}.service-row h2{margin:8px 0}.danger{color:var(--danger)}.notice{padding:13px 16px;border-radius:8px;margin-bottom:18px;background:#e7f5ed}.notice.error{background:#fff0ef}.modal-backdrop{position:fixed;inset:0;z-index:5;display:grid;place-items:center;padding:18px;background:rgba(23,32,42,.45)}.modal{width:min(560px,100%);max-height:90vh;overflow:auto}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}@media(max-width:560px){.service-row{align-items:flex-start;flex-direction:column}.form-grid{grid-template-columns:1fr}}</style>