<template>
  <section><div class="page-header"><div><p class="eyebrow">Settings</p><h1>Booking profile</h1><p class="lede">This information appears on every public booking page. Goalmatic remains the account authority.</p></div><span class="chip">v0.1.0</span></div>
    <div v-if="notice" class="notice" role="status">{{ notice }}</div><div v-if="error" class="notice error" role="alert">{{ error }}</div>
    <div class="grid grid-2"><form class="card" @submit.prevent="submit"><h2>Public identity</h2><div class="field"><label>Display name</label><input v-model.trim="form.displayName" maxlength="160" required></div><div class="field"><label>Short bio</label><textarea v-model.trim="form.bio" maxlength="1500"></textarea></div><div class="field"><label>Timezone</label><input v-model.trim="form.timezone" required placeholder="Africa/Lagos"></div><div class="field"><label>Photo URL</label><input v-model.trim="form.photoUrl" type="url" placeholder="https://…"></div><button class="primary" :disabled="saving">{{ saving?'Saving…':'Save profile' }}</button></form>
      <article class="card"><h2>Public booking link</h2><p class="muted">The link is bound to this installation and release. Revoking it immediately stops future guest access.</p><div v-if="publicUrl" class="link"><code>{{ publicUrl }}</code><div class="form-actions"><button class="secondary" type="button" @click="copy">Copy link</button><a class="secondary action" :href="publicUrl" target="_blank" rel="noreferrer">Open</a><button class="danger" type="button" @click="confirmRevoke=true">Revoke</button></div><p class="muted">Expires {{ expires }}</p></div><button v-else class="primary" type="button" :disabled="linking||!canShare" @click="createLink">{{ linking?'Creating…':'Create booking link' }}</button><p v-if="!canShare" class="muted">Save a profile, availability, and one active service first.</p><div v-if="confirmRevoke" class="confirm-box"><strong>Revoke this link?</strong><p class="muted">Anyone using it will see an expired-link state.</p><div class="form-actions"><button class="danger" type="button" @click="revoke">Revoke link</button><button class="secondary" type="button" @click="confirmRevoke=false">Keep link</button></div></div></article></div>
  </section>
</template>
<script setup>
import { computed,inject,onMounted,reactive,ref } from 'vue';import { createPublicLink,revokePublicLink,saveProfile } from '../booking.js'
const state=inject('bookingState'),refresh=inject('refreshBookings'),saving=ref(false),linking=ref(false),confirmRevoke=ref(false),notice=ref(''),error=ref('')
const form=reactive({displayName:'',bio:'',timezone:'Africa/Lagos',photoUrl:''})
const publicUrl=computed(()=>state.profile?.['public-link-url']||''),expires=computed(()=>state.profile?.['public-link-expires-at']?new Date(state.profile['public-link-expires-at']).toLocaleDateString():'unknown'),canShare=computed(()=>!!state.profile&&!!state.schedules.length&&state.services.some(item=>item.active!==false))
onMounted(()=>{if(state.profile)Object.assign(form,{displayName:state.profile['display-name']||'',bio:state.profile.bio||'',timezone:state.profile.timezone||'Africa/Lagos',photoUrl:state.profile['photo-url']||''})})
async function submit(){saving.value=true;error.value='';try{await saveProfile(state.profile,{...form,publicLinkUrl:publicUrl.value,publicLinkExpiresAt:state.profile?.['public-link-expires-at']||''});await refresh();notice.value='Profile saved.'}catch(reason){error.value=reason?.message||'Profile could not be saved.'}finally{saving.value=false}}
async function createLink(){linking.value=true;error.value='';try{const result=await createPublicLink({kind:'profile'});const url=`${location.origin}${result.routePath||'/book'}#${result.token}`;await saveProfile(state.profile,{...form,publicLinkUrl:url,publicLinkExpiresAt:result.expiresAt});await refresh();notice.value='Public booking link created.'}catch(reason){error.value=reason?.message||'Public link could not be created.'}finally{linking.value=false}}
async function revoke(){error.value='';try{await revokePublicLink(publicUrl.value);await saveProfile(state.profile,{...form,publicLinkUrl:'',publicLinkExpiresAt:''});await refresh();notice.value='Public link revoked.';confirmRevoke.value=false}catch(reason){error.value=reason?.message||'Public link could not be revoked.'}}
async function copy(){await navigator.clipboard.writeText(publicUrl.value);notice.value='Link copied.';setTimeout(()=>notice.value='',1600)}
</script>
<style scoped>.action{display:inline-flex;align-items:center;text-decoration:none;padding:0 16px}.link code{display:block;padding:13px;margin:18px 0 12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;border-radius:10px;background:#f2f3f8}.confirm-box{padding:16px;margin-top:18px;border-radius:12px;background:#fff5f4}.confirm-box p{margin:5px 0 12px}
</style>
